##
## Build
##
FROM golang:alpine3.15 AS builder

WORKDIR /builder

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY ./ ./
RUN CGO_ENABLED=0 GOOS=linux go build -o ./chattweiler ./cmd/main.go

##
## Deploy
##
FROM gcr.io/distroless/base-debian11

WORKDIR /application

COPY --from=builder ./builder/chattweiler ./chattweiler

CMD ["./chattweiler"]