##
## Build
##
FROM golang:alpine3.15 AS builder

WORKDIR /builder

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY ./ ./

RUN CGO_ENABLED=0 GOOS=linux go build -o ./chattweiler ./cmd/main.go

##
## Deploy
##
FROM gcr.io/distroless/base-debian11

WORKDIR /deploy

COPY --from=builder ./builder/chattweiler ./chattweiler

CMD ["./chattweiler"]